/**:
  ros__parameters:
    stack_topic: "stack"
    twin_topic: "twin"
    agent_to_gateway_topic: "agent_to_gateway"
    gateway_to_agent_topic: "gateway_to_agent"
    agent_to_commands_topic: "agent_to_command"
    commands_to_agent_topic: "command_to_agent"
    thing_messages_topic: "thing_messages"
    ignored_packages: [""]


    twin_url: "https://ditto:ditto@sandbox.composiv.ai"
    host: sandbox.composiv.ai
    port: 1883
    keep_alive: 60
    user: null
    password: null
    anonymous: true
    type: real_car
    attributes: '{"brand": "muto", "model": "composer"}'
    prefix: muto
    namespace: org.eclipse.muto.sandbox
    name: hack2025-01

    symphony_enabled: True
    symphony_name: "hack2025-01"
    symphony_target_name: "muto-device-001"
    symphony_topic_prefix: "muto"
    symphony_host: "192.168.0.47"
    symphony_port: 1883
    symphony_keep_alive: 60
    symphony_prefix: muto
    symphony_user: "admin"
    symphony_password: ""

    # Symphony API configuration
    symphony_api_url: "http://192.168.0.47:8082/v1alpha2/"
    symphony_provider_name: "providers.target.mqtt"
    symphony_broker_address: "tcp://mosquitto:1883"
    symphony_client_id: "symphony"
    symphony_request_topic: "coa-request"
    symphony_response_topic: "coa-response"
    symphony_timeout_seconds: "30"
    symphony_auto_register: False


    commands:
      command1:
        name: ros/topic
        service: rostopic_list
        plugin: CommandPlugin

      command2:
        name: ros/topic/info
        service: rostopic_info
        plugin: CommandPlugin

      command3:
        name: ros/topic/echo
        service: rostopic_echo
        plugin: CommandPlugin

      command4:
        name: ros/node
        service: rosnode_list
        plugin: CommandPlugin

      command5:
        name: ros/node/info
        service: rosnode_info
        plugin: CommandPlugin

      command6:
        name: ros/param
        service: rosparam_list
        plugin: CommandPlugin

      command7:
        name: ros/param/get
        service: rosparam_get
        plugin: CommandPlugin
